from src.AST.calc import *
from src.AST.cmp import *
from src.AST.data_types import *
from src.AST.io import *
from src.AST.logic import *
from src.AST.program import *
from src.AST.var import *
from src.AST.function import *
from src.AST.array import *
from src.AST.insert_func import *
