from .calc import *
from .cmp import *
from .data_types import *
from .io import *
from .logic import *
from .program import *
from .var import *
from .function import *
from .array import *
from .insert_func import *
from .file import *
from .types import *
