name: 功能建议
description: "如果你想建议一些新的功能，请使用此模板。"
labels: ["功能"]
body: 
  - type: markdown
    attributes:
      value: |
        发Issue前请先看看Issue列表里有没有你的建议，包括已关闭的建议。如有，请关注相关Issue而不是重复建议。
        如果你只有相关功能的构想而不清楚如何实际实现相关功能，请先在[讨论·Discussions](https://github.com/CreatechStudio/MC-Mod-Integration/discussions)提出。
        请在标题栏中用最简练的语言清晰的描述你的建议。
        如果你具有相关能力，请开Pull Request而不是开Issue，这样能节约你我的时间。
  - type: textarea
    id: description
    attributes: 
      label: 功能描述
      description: 在下方的编辑框描述你想要的功能
      placeholder: 请尽可能完整说明你的建议，包括相关功能应该如何正确工作、何时工作等。
    validations:
      required: true
  - type: textarea
    id: mod
    attributes: 
      label: 想要添加的模组名与介绍链接
      description: 在下方的编辑框描述你想添加的这个模组，并附上介绍链接，若没有链接或模组名称不明，将会被直接关闭或标记为需要更多信息（多个模组需换行请直接回车，会为你添加标号）
      placeholder: 能看到这个？说明你没有看描述，请自己加上“1. ”
      value: "1. "
    validations:
      required: true
  - type: textarea
    id: extra
    attributes: 
      label: 额外说明
      description: 还有什么要补充的吗？
