name: 功能建议
description: "如果你想建议一些新的功能，请使用此模板。"
labels: ["功能"]
body:
  - type: markdown
    attributes:
      value: |
        发Issue前请先看看Issue列表里有没有你的建议，包括已关闭的建议。如有，请关注相关Issue而不是重复建议。
        如果你只有相关功能的构想而不清楚如何实际实现相关功能，请先在[讨论·Discussions](https://github.com/iewnfod/CAIE_Code/discussions)提出。
        请在标题栏中用最简练的语言清晰的描述你的建议。
        如果你具有相关能力，请开Pull Request而不是开Issue，这样能节约你我的时间。
  - type: textarea
    id: description
    attributes:
      label: 功能描述
      description: 在下方的编辑框描述你想要的功能
      placeholder: 请尽可能完整说明你的建议，包括相关功能应该如何正确工作、何时工作等。
    validations:
      required: true
  - type: textarea
    id: example
    attributes:
      label: 功能样例
      description: 展示这样功能的例子，可以是某些语法，也可以是实现以后能够做到什么。
      placeholder: 能看到这个？说明你没有看描述，请自己加上“1. ”
      value: "1. "
    validations:
      required: true
  - type: textarea
    id: extra
    attributes:
      label: 额外说明
      description: 还有什么要补充的吗？
