name: Update Chocolatey Package & Releases

on:
  workflow_dispatch:
  push:
    branches:
      - stable

jobs:
  publish:
    runs-on: windows-latest

    steps:
      - name: Checkout stable branch
        uses: actions/checkout@v4
        with:
          ref: stable

      - name: Pack Chocolatey Package
        run: choco pack choco-pkg/caie-code.nuspec --outputdirectory choco-pkg

      - name: Find .nupkg File
        id: find_nupkg
        run: |
          $nupkgFile = Get-ChildItem -Path choco-pkg -Filter *.nupkg | Select-Object -ExpandProperty Name
          if (-Not $nupkgFile) { Write-Host "No .nupkg file found!"; exit 1 }
          echo "NUPKG_FILE=$nupkgFile" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Read VERSION file
        id: read_version
        run: |
          $version = Get-Content VERSION -Raw
          $version = $version.Trim()
          echo "VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Get latest commit hash
        id: get_commit_hash
        run: |
          $commitHash = git rev-parse --short HEAD
          echo "COMMIT_HASH=$commitHash" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Generate tag
        id: generate_tag
        run: |
          $tag = "v${{ env.VERSION }}-${{ env.COMMIT_HASH }}"
          echo "TAG_NAME=$tag" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Create GitHub Tag
        run: |
          git tag ${{ env.TAG_NAME }}
          git push origin ${{ env.TAG_NAME }}

      - name: Create GitHub Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ env.TAG_NAME }}
          tag: ${{ env.TAG_NAME }}
          artifacts: choco-pkg/${{ env.NUPKG_FILE }}
          generateReleaseNotes: true
          makeLatest: true
